version: "3"
services:
  azure-cis-scanner:
    image: ${AZURE_CIS_SCANNER_IMAGE} 
    volumes:
      - ${ENGAGEMENTS_DIR}:/engagements
      - ${AZURE_CONFIG_DIR}:/root/.azure
    ports:
      - ${JUPYTER_PORT}:8888
      - ${FLASK_PORT}:5000
    # the --port=8888 refers to the port inside the container, do not change
    entrypoint: ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--allow-root"]
      