version: "3"
services:
  azure-cis-scanner:
    image: kbroughton/azure-cis-scanner-apline:0.2
    volumes:
      - ${ENGAGEMENTS_DIR}:/engagements
      - "./.azure:/root/.azure" 
    ports:
      - ${JUPYTER_PORT}:8888
      - ${FLASK_PORT}:5000
    entrypoint: ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--allow-root"]
