version: "3"
services:
  azure-cis-scanner:
    image: ${AZURE_CIS_SCANNER_IMAGE}
    volumes:
      - ./:/notebooks/azure_cis_scanner             # Development
      - ${ENGAGEMENTS_DIR}:/engagements
      - ${AZURE_CONFIG_DIR}:/root/.azure 
    ports:
      - ${JUPYTER_PORT}:8888
      - ${FLASK_PORT}:5000
    entrypoint: ["jupyter", "notebook", "--port=8888", "--ip=0.0.0.0", "--allow-root"]
